"""agregar constraints clientes table

Revision ID: 26011220e2dd
Revises: a405b8f93df4
Create Date: 2025-12-26 12:40:21.191759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26011220e2dd'
down_revision = 'a405b8f93df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
