"""add documentos and tipo_documento enum

Revision ID: e22b900a1801
Revises: 26011220e2dd
Create Date: 2025-12-26 12:53:32.167440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22b900a1801'
down_revision = '26011220e2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_documento', sa.String(length=40), nullable=False),
    sa.Column('tipo_documento', sa.Enum('NIT', 'CEDULA', 'PASAPORTE', name='tipo_documento_enum'), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(numero_documento) > 0', name='ck_doc_numero_no_vacio'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id'),
    sa.UniqueConstraint('tipo_documento', 'numero_documento', name='uq_doc_tipo_numero')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.drop_table('documentos')
    # ### end Alembic commands ###
