"""add compra producto detalle_compra

Revision ID: fe1722706f80
Revises: e22b900a1801
Create Date: 2025-12-26 13:27:57.141196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1722706f80'
down_revision = 'e22b900a1801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(nombre) > 0', name='ck_producto_nombre_no_vacio'),
    sa.CheckConstraint('precio >= 0', name='ck_producto_precio_no_negativo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETADA', 'CANCELADA', 'REEMBOLSADA', name='estado_compra_enum'), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('monto_total > 0', name='ck_compra_monto_no_negativo_ni_cero'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compras_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('detalles_compra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cantidad_compra', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('compra_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('cantidad_compra > 0', name='ck_detalle_cantidad_mayor_que_cero'),
    sa.CheckConstraint('precio_unitario >= 0', name='ck_detalle_precio_unitario_no_negativo'),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compra_id', 'producto_id', name='uq_detalle_compra_producto')
    )
    with op.batch_alter_table('detalles_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detalles_compra_compra_id'), ['compra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detalles_compra_producto_id'), ['producto_id'], unique=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('detalles_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detalles_compra_producto_id'))
        batch_op.drop_index(batch_op.f('ix_detalles_compra_compra_id'))

    op.drop_table('detalles_compra')
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compras_cliente_id'))

    op.drop_table('compras')
    op.drop_table('productos')
    # ### end Alembic commands ###
